name: shiny_dashboard_environment
dependencies:
  - r-base=4.1.3
  - dplyr=1.1.4
  - readr=2.1.5
  - countrycode=1.6.0
  - plotly=4.10.2
  - ggplot2=3.4.2
  - shiny=1.7.4
  - rcpp=1.0.12
  - later=1.3.2
  - bslib=0.5.0
  - pillar=1.9.0
  - compiler=4.1.3
  - tools=4.1.3
  - digest=0.6.35
  - memoise=2.0.1
  - viridislite=0.4.1
  - jsonlite=1.8.8
  - lifecycle=1.0.3
  - tibble=3.2.1
  - gtable=0.3.3
  - pkgconfig=2.0.3
  - rlang=1.1.3
  - cli=3.6.2
  - crosstalk=1.2.0
  - yaml=2.3.8
  - fastmap=1.1.1
  - withr=2.5.0
  - httr=1.4.6
  - maps=3.4.1
  - sass=0.4.9
  - hms=1.1.3
  - generics=0.1.3
  - vctrs=0.6.5
  - htmlwidgets=1.6.2
  - grid=4.1.3
  - tidyselect=1.2.0
  - glue=1.7.0
  - data.table=1.15.2
  - r6=2.5.1
  - fansi=1.0.6
  - tzdb=0.4.0
  - tidyr=1.3.1
  - purrr=1.0.2
  - magrittr=2.0.3
  - scales=1.2.1
  - promises=1.2.1
  - ellipsis=0.3.2
  - htmltools=0.5.8
  - mime=0.12
  - xtable=1.8-4
  - colorspace=2.1-0
  - httpuv=1.6.15
  - labeling=0.4.2
  - utf8=1.2.4
  - lazyeval=0.2.2
  - munsell=0.5.0
  - cachem=1.0.8
  - crayon=1.5.2
